### ISSUE TITLE
What will you be adding?

### ISSUE THREAD

**Issue by RobLoach** [leiradel/retroluxury#3]
Just a note that the latest changes fixed it, and it's terrifying:

> `retroarch -L test.dll`

![RetroLuxury](https://cloud.githubusercontent.com/assets/25086/16110336/3b7af32e-337b-11e6-99c7-46d3a81b85ed.jpg)

What will you be adding to RetroLuxury?

**Comment by leiradel** [comment]
Hm, I've only tested on Windows and the tearing is not there. Do you have vsync turned on?

I'm working on [Tiled](http://www.mapeditor.org/) support, and maybe support for a free sprite animation and atlas tool. The intention is to have a framework that has support for free gamedev tools and, because of that, is easy to use to build retro-looking games for the libretro platform.

I also have plans to write bindings for the Lua language, but I won't even try to make it compatible with Löve 2D, the objectives are different and so will be the bindings.

If you have more feedbacks and/or suggestions I'd love to hear!

**Comment by RobLoach** [comment]
> I've only tested on Windows and the tearing is not there. Do you have vsync turned on?

The tearing you see in the screenshot is probably because of the screenshot tool I used. It looks smooth in realtime. This is on Ubuntu 16.04, and works well.

> I also have plans to write bindings for the Lua language, but I won't even try to make it compatible with Löve 2D, the objectives are different and so will be the bindings.

Regarding Lua, I recently ran into [Wren](http://wren.io/), which looks to be a lot [easier to bind](https://github.com/munificent/wren/wiki/Language-Bindings). Would make it stand on its own beside [Lutro](https://github.com/libretro/libretro-lutro)/Love.

**Comment by leiradel** [comment]
> The tearing you see in the screenshot is probably because of the screenshot tool I used. It looks smooth in realtime. This is on Ubuntu 16.04, and works well.

Ah, I think I misunderstood your use of "terrifying" as something bad :)

> Regarding Lua, I recently ran into Wren, which looks to be a lot easier to bind. Would make it stand on its own beside Lutro/Love.

Wow, Wren definitely looks awesome! My concerns are, I'm **very** familiar with Lua (the language, how to embed and to bind), and from a quick glance at Wren, Lua syntax seems easier understand.

**Comment by RobLoach** [comment]
Keep it up! Been loving seeing how RetroLuxury has progressed. With some inspiration from RetroLuxury, I put together a test with Cairo: https://github.com/robloach/libretro-cairo

Unsure it builds anywhere. Just thought I'd link it here. Going to close this issue in the meantime. Thanks!

**Comment by leiradel** [comment]
> With some inspiration from RetroLuxury, I put together a test with Cairo: https://github.com/robloach/libretro-cairo

Very interesting! Is it fast enough for games?

**Comment by RobLoach** [comment]
> Is it fast enough for games?

Haven't tried benchmarking it. Would love to try though.
